# Generated by Django 3.2.6 on 2021-08-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_auto_20210822_1734'),
        ('employee', '0005_merge_0003_auto_20210822_0339_0004_auto_20210822_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='asigned_by_admin',
            new_name='assigned_by_admin',
        ),
        migrations.AddField(
            model_name='policy',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.resource'),
        ),
        migrations.AddField(
            model_name='policy',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.seat'),
        ),
    ]
