# Generated by Django 3.2.6 on 2021-08-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('work_position', models.ManyToManyField(to='employee.BaseWorkGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ContagiousHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcr_result', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative')], max_length=1)),
                ('fecha_sintomas', models.DateField(blank=True, null=True, verbose_name='Fecha de Sintomas')),
                ('fecha_reporte', models.DateField(blank=True, null=True, verbose_name='Fecha de Reporte')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagioushistory_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
