# Generated by Django 3.2.6 on 2021-08-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='created_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='policy',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
