# Generated by Django 3.2.6 on 2021-08-22 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_auto_20210821_2024'),
        ('employee', '0003_auto_20210822_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='work_position',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='horario',
        ),
        migrations.AddField(
            model_name='policy',
            name='days_of_the_week',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='dias de asistencia'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_area_id', to='infrastructure.area'),
        ),
        migrations.DeleteModel(
            name='BaseWorkGroup',
        ),
        migrations.DeleteModel(
            name='WorkGroup',
        ),
    ]
