# Generated by Django 3.2.6 on 2021-08-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210822_0339'),
        ('employee', '0004_auto_20210822_0336'),
    ]

    operations = [
    ]
