# Generated by Django 3.2.6 on 2021-08-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone_number',
            field=models.CharField(max_length=15, verbose_name='Numero telefono'),
        ),
    ]
