# Generated by Django 3.2.6 on 2021-08-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210821_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero telefono'),
        ),
    ]
