# Generated by Django 3.2.6 on 2021-08-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_auto_20210821_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchofficeconfig',
            name='maximun_capacity',
        ),
        migrations.AlterField(
            model_name='location',
            name='fase',
            field=models.CharField(choices=[('FASEI', 'Fase I'), ('FASEII', 'Fase II'), ('FASEIII', 'Fase III'), ('FASEIV', 'Fase IV')], max_length=250),
        ),
    ]
