# Generated by Django 3.2.6 on 2021-08-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_auto_20210822_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='level',
            new_name='admnistrative_level',
        ),
        migrations.RemoveField(
            model_name='location',
            name='fase',
        ),
        migrations.AddField(
            model_name='areaconfig',
            name='fase',
            field=models.CharField(choices=[('FASEI', 'Fase I'), ('FASEII', 'Fase II'), ('FASEIII', 'Fase III'), ('FASEIV', 'Fase IV')], default='', max_length=250),
            preserve_default=False,
        ),
    ]
