# Generated by Django 3.2.6 on 2021-08-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20210822_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='area',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='areaconfig',
            name='maximun_request_days_contagious',
        ),
        migrations.RemoveField(
            model_name='branchofficeconfig',
            name='maximun_request_days',
        ),
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default='legacy', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areaconfig',
            name='maximun_request_days_ahead',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='resource',
            name='area',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='tipo',
            field=models.CharField(choices=[('ESCRITORIO IND', 'Escritorio individual'), ('SALA DE REUNIÓN', 'Sala de reunión'), ('PARQUEADERO', 'Parqueadero'), ('ESCRITORIO COMP', 'Escritorio compartido')], default='ESCRITORIO COMP', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areaconfig',
            name='fase',
            field=models.CharField(choices=[('FASEI', 'Fase I'), ('FASEII', 'Fase II'), ('FASEIII', 'Fase III'), ('FASEIV', 'Fase IV'), ('FASEIV', 'Fase V'), ('Sin fase', 'Sin fase')], max_length=250),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_area', models.IntegerField(verbose_name='Id del asiento dentro del area')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.resource')),
            ],
        ),
    ]
