# Generated by Django 3.2.6 on 2021-08-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_auto_20210822_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='branch_office',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.branchoffice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='branch_offices',
            field=models.ManyToManyField(to='infrastructure.BranchOffice'),
        ),
        migrations.DeleteModel(
            name='BranchOfficeEmployee',
        ),
    ]
