# Generated by Django 3.2.6 on 2021-08-22 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_auto_20210822_1633'),
        ('infrastructure', '0006_auto_20210822_1746'),
    ]

    operations = [
    ]
