# Generated by Django 3.2.6 on 2021-08-23 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructure', '0008_alter_areaconfig_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='employee',
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
