# Generated by Django 3.2.6 on 2021-08-23 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructure', '0009_auto_20210823_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchoffice',
            name='branch_office_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.branchofficeconfig'),
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='employee',
        ),
        migrations.AddField(
            model_name='reserva',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
