# Generated by Django 3.2.6 on 2021-08-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_auto_20210823_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='start_date',
        ),
        migrations.AddField(
            model_name='reserva',
            name='resource',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.seat'),
        ),
    ]
