# Generated by Django 3.2.6 on 2021-08-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_auto_20210823_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchofficeconfig',
            name='days_to_review_contagious',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
