# Generated by Django 3.2.6 on 2021-08-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_alter_branchofficeconfig_maximun_request_days_contagious'),
        ('infrastructure', '0012_auto_20210823_1446'),
    ]

    operations = [
    ]
