# Generated by Django 3.2.6 on 2021-08-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_branchofficeconfig_days_to_review_contagious'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='branch_area_config',
        ),
        migrations.AddField(
            model_name='areaconfig',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='areaconfig',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='fase',
            field=models.CharField(choices=[('FASEI', 'Fase I'), ('FASEII', 'Fase II'), ('FASEIII', 'Fase III'), ('FASEIV', 'Fase IV'), ('FASEV', 'Fase V'), ('Sin fase', 'Sin fase')], default='Sin fase', max_length=250),
            preserve_default=False,
        ),
    ]
