# Generated by Django 3.2.6 on 2021-08-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_branchofficeconfig_days_to_review_contagious'),
        ('infrastructure', '0013_merge_20210823_1533'),
    ]

    operations = [
    ]
