# Generated by Django 3.2.6 on 2021-08-23 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infrastructure', '0014_merge_20210823_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchofficeconfig',
            name='days_to_review_contagious',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='employee',
        ),
        migrations.AddField(
            model_name='reserva',
            name='employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='end_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='start_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada'),
        ),
    ]
