# Generated by Django 3.2.6 on 2021-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0015_merge_20210823_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchofficeconfig',
            name='maximun_request_days_contagious',
            field=models.IntegerField(default=14),
        ),
    ]
