# Generated by Django 3.2.6 on 2021-08-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_auto_20210823_1623'),
        ('infrastructure', '0015_auto_20210823_1616'),
    ]

    operations = [
    ]
