# Generated by Django 3.2.6 on 2021-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_alter_branchofficeconfig_maximun_request_days_contagious'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchofficeconfig',
            name='days_to_review_contagious',
            field=models.IntegerField(default=0),
        ),
    ]
