# Generated by Django 3.2.6 on 2021-08-25 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0018_alter_areaconfig_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='fase',
            field=models.CharField(choices=[('FASEI', 'Fase I'), ('FASEII', 'Fase II'), ('FASEIII', 'Fase III'), ('FASEIV', 'Fase IV'), ('Sin fase', 'Sin fase')], max_length=250),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.resource'),
        ),
    ]
