# Generated by Django 3.2.6 on 2021-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20210822_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaconfig',
            name='end_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada area fin'),
        ),
        migrations.AlterField(
            model_name='areaconfig',
            name='start_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada area inicio'),
        ),
        migrations.AlterField(
            model_name='branchofficeconfig',
            name='end_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada fin'),
        ),
        migrations.AlterField(
            model_name='branchofficeconfig',
            name='start_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada inicio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='end_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='start_date',
            field=models.TimeField(blank=True, null=True, verbose_name='hora jornada'),
        ),
    ]
