# Generated by Django 3.2.6 on 2021-08-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('maximun_capacity', models.IntegerField(default=0)),
                ('tipo', models.CharField(choices=[('ESCRITORIO', 'Escritorio'), ('SALA DE REUNIÓN', 'Sala de reunión')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximun_capacity', models.IntegerField(default=0)),
                ('immobile_spaces', models.IntegerField(default=0, verbose_name='Cantidad espacios fijos')),
                ('flexible_spaces', models.IntegerField(default=0, verbose_name='Cantidad espacios flexibles')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='hora jornada area inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='hora jornada area fin')),
                ('maximun_request_days_contagious', models.IntegerField(default=14)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOfficeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximun_capacity', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='hora jornada inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='hora jornada fin')),
                ('maximun_request_days', models.IntegerField(default=1)),
                ('maximun_request_days_contagious', models.IntegerField(default=14)),
                ('notify_branch_office', models.BooleanField(default=False)),
                ('block_branch_office', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fijo', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='hora jornada')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='hora jornada')),
                ('status', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_area_id', to='infrastructure.area')),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_branchoffice_id', to='infrastructure.branchoffice')),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('COMUNA', 'Comuna')], max_length=20)),
                ('fase', models.CharField(max_length=250)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_country_id', to='infrastructure.country')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('minimum_attendance', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='fecha contratación')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha fin de contratación')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_company_id', to='infrastructure.company')),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BranchOfficeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('branch_office', models.ManyToManyField(to='infrastructure.BranchOffice')),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='branch_office_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchoffice_branchofficeconfig_id', to='infrastructure.branchofficeconfig'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchoffice_company_id', to='infrastructure.company'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchoffice_country_id', to='infrastructure.country'),
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchoffice_location_id', to='infrastructure.location'),
        ),
        migrations.AddField(
            model_name='area',
            name='branch_area_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaconfig_id', to='infrastructure.areaconfig'),
        ),
    ]
