# Generated by Django 3.2.6 on 2021-08-21 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('compartible', models.BooleanField(default=False)),
                ('reservable', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='branchoffice',
            name='country',
        ),
        migrations.AlterField(
            model_name='area',
            name='branch_area_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_areaConfig_id', to='infrastructure.areaconfig'),
        ),
        migrations.AddField(
            model_name='area',
            name='resource',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='area_resource_id', to='infrastructure.resource'),
            preserve_default=False,
        ),
    ]
